---
ID: "ba8069ff-8796-4551-83d7-2282d75c49dd"
Parent: "1be3c950-4f9b-4ad7-bccb-0253e88f4882"
Template: "1be3c950-4f9b-4ad7-bccb-0253e88f4882"
Path: /sitecore/templates/Site/DefaultPage/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{DAEB1775-D9C5-49D9-9420-E66E0E62BC4E}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180803T161435Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
